language: go
sudo: false

matrix:
  include:
  - go: 1.13.x
  - go: 1.14.x

script:
  - make lint
  - make test
  - make bench
  - make cmds

after_success:
  - make cover
  - bash <(curl -s https://codecov.io/bash)